[MATLAB_PATHS]
#Główne ścieżki do skryptów startowych
peaq_root = matlab_scripts/PEAQ
visqol_root = matlab_scripts/VisqolA

#Podfoldery wymagane przez algorytm PEAQ (PQevalAudio)
pqeval_root = matlab_scripts/PEAQ/PQevalAudio
pqeval_cb   = matlab_scripts/PEAQ/PQevalAudio/CB
pqeval_misc = matlab_scripts/PEAQ/PQevalAudio/Misc
pqeval_mov  = matlab_scripts/PEAQ/PQevalAudio/MOV
pqeval_patt = matlab_scripts/PEAQ/PQevalAudio/Patt